name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format
version: 1.8.0
topics:
  - code-style
  - formatting

environment:
  sdk: ^3.10.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  analyzer: ^10.1.0
  freezed_annotation: ^3.1.0
  eggnstone_dart: ^1.4.2
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.10.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  meta: ^1.18.1
  test: any

dependency_overrides:
  #

assets:
  - assets/favicon.ico
